development:
  adapter: postgresql
  encoding: utf8
  reconnect: true
  database: ruby_basic_development
  host: localhost
  port: 5432
  pool: 5
  username: postgres
  password: sqlsecret

test:
  adapter: postgresql
  encoding: utf8
  reconnect: true
  database: ruby_basic_test
  host: localhost
  port: 5432
  pool: 5
  username: postgres
  password: sqlsecret

production:
  adapter: postgresql
  encoding: utf8
  reconnect: true
  database: ruby_basic_production
  host: localhost
  port: 5432
  pool: 5
  username: postgres
  password:
